// Mock data for development/demo mode
// When Firebase is connected, this data will be replaced by real Firestore data

export const mockUser = {
  uid: 'user_001',
  nickname: '밤하늘',
  username: '@nightsky_',
  email: 'user@plin.app',
  profileEmoji: '🌙',
  isPublic: true,
  concertCount: 28,
  friendCount: 142,
  joinedAt: '2024-01-15',
  favoriteArtists: ['aespa', 'NewJeans', 'BTS'],
};

export const mockRecords = [
  {
    id: 'rec_001',
    concertName: 'aespa MY WORLD TOUR in Seoul',
    artist: 'aespa',
    venue: '고척스카이돔',
    venueAddress: '서울 구로구 경인로 430',
    date: '2025-11-15',
    time: '19:00',
    emotion: '🔥',
    weather: '⛅',
    mood: '흥분',
    rating: 5,
    isPublic: true,
    lat: 37.4981,
    lng: 126.8670,
    setlist: [
      'Supernova', 'Drama', 'Spicy', 'Girls', 'Next Level',
      'Black Mamba', 'Savage', 'Hold On Tight', 'Better Things', 'Whiplash'
    ],
    photos: [],
    memo: '인생 공연이었다. 카리나 눈 마주쳤음 확실히... SYNK: Parallel Line 세트가 너무 완벽했어. 내년에도 꼭 가야지!',
    tags: ['aespa', '고척', '세계투어', '인생공연'],
  },
  {
    id: 'rec_002',
    concertName: 'NewJeans Bunnies Camp 2025',
    artist: 'NewJeans',
    venue: '잠실올림픽주경기장',
    venueAddress: '서울 송파구 올림픽로 25',
    date: '2025-09-07',
    time: '18:00',
    emotion: '💕',
    weather: '☀️',
    mood: '설레임',
    rating: 5,
    isPublic: true,
    lat: 37.5172,
    lng: 127.0615,
    setlist: [
      'Attention', 'Hype Boy', 'Cookie', 'Ditto', 'OMG',
      'ETA', 'Super Shy', 'NewJeans', 'Zero', 'Right Now'
    ],
    photos: [],
    memo: '버니즈로서 처음 가는 콘서트! 민지가 한국어로 직접 말해줬을 때 진짜 울뻔했다',
    tags: ['NewJeans', '잠실', '버니즈캠프'],
  },
  {
    id: 'rec_003',
    concertName: 'IU H.E.R. World Tour',
    artist: 'IU',
    venue: '올림픽체조경기장',
    venueAddress: '서울 송파구 올림픽로 424',
    date: '2025-06-20',
    time: '19:30',
    emotion: '😭',
    weather: '🌧️',
    mood: '감동',
    rating: 5,
    isPublic: true,
    lat: 37.5203,
    lng: 127.0646,
    setlist: [
      '밤편지', '팔레트', '좋은 날', '스물셋', '나의 옛날 이야기',
      'Celebrity', 'LILAC', 'Blueming', '이 지금', 'Through the Night'
    ],
    photos: [],
    memo: '비 오는 날 야외에서 밤편지 들을 때 진짜 눈물 줄줄... 이게 공연이지',
    tags: ['IU', '아이유', '월드투어'],
  },
];

export const mockConcerts = [
  {
    id: 'con_001',
    name: 'BLACKPINK WORLD TOUR [BORN PINK] ENCORE',
    artist: 'BLACKPINK',
    artistImage: '🖤',
    venue: '고척스카이돔',
    city: '서울',
    date: '2026-06-14',
    time: '18:00',
    genre: ['K-POP', '팝'],
    ticketingDate: '2026-04-20',
    ticketingUrl: 'https://ticket.interpark.com',
    price: '99,000 ~ 165,000원',
    status: 'upcoming',
    isBookmarked: false,
    reviewCount: 0,
    description: '블랙핑크 월드투어 앙코르 서울 공연',
  },
  {
    id: 'con_002',
    name: 'BTS PERMISSION TO DANCE ON STAGE',
    artist: 'BTS',
    artistImage: '💜',
    venue: '잠실올림픽주경기장',
    city: '서울',
    date: '2026-07-05',
    time: '19:00',
    genre: ['K-POP'],
    ticketingDate: '2026-05-01',
    ticketingUrl: 'https://ticket.yes24.com',
    price: '110,000 ~ 200,000원',
    status: 'upcoming',
    isBookmarked: true,
    reviewCount: 0,
    description: 'BTS 단독 콘서트',
  },
  {
    id: 'con_003',
    name: 'aespa SYNK: Parallel Line WORLD TOUR',
    artist: 'aespa',
    artistImage: '🤍',
    venue: 'KSPO DOME',
    city: '서울',
    date: '2026-08-22',
    time: '18:30',
    genre: ['K-POP'],
    ticketingDate: '2026-06-10',
    ticketingUrl: 'https://ticket.interpark.com',
    price: '99,000 ~ 165,000원',
    status: 'upcoming',
    isBookmarked: false,
    reviewCount: 2,
    description: 'aespa 두 번째 월드투어',
  },
  {
    id: 'con_004',
    name: 'Coldplay Music of the Spheres World Tour',
    artist: 'Coldplay',
    artistImage: '🌈',
    venue: '서울월드컵경기장',
    city: '서울',
    date: '2026-05-28',
    time: '19:30',
    genre: ['팝', '록'],
    ticketingDate: '2026-03-15',
    ticketingUrl: 'https://ticket.interpark.com',
    price: '99,000 ~ 220,000원',
    status: 'sold_out',
    isBookmarked: true,
    reviewCount: 847,
    description: '콜드플레이 내한 공연',
  },
  {
    id: 'con_005',
    name: 'NewJeans 2nd Concert: The Bunnies',
    artist: 'NewJeans',
    artistImage: '🐰',
    venue: '올림픽체조경기장',
    city: '서울',
    date: '2026-09-13',
    time: '18:00',
    genre: ['K-POP'],
    ticketingDate: '2026-07-20',
    ticketingUrl: 'https://ticket.yes24.com',
    price: '88,000 ~ 143,000원',
    status: 'upcoming',
    isBookmarked: false,
    reviewCount: 0,
    description: '뉴진스 두 번째 단독 콘서트',
  },
];

export const mockPosts = [
  {
    id: 'post_001',
    author: {
      uid: 'user_002',
      nickname: '별빛수집가',
      profileEmoji: '⭐',
      isPublic: true,
    },
    content: '어제 aespa 공연 다녀왔는데 진짜 인생 공연이었어요 😭💗 카리나 직캠 보시면 왜 제가 이러는지 이해하실 거예요... 슈퍼노바 무대 올라왔을 때 소름 쫙 돋았어요. 다음 투어도 꼭 가야겠다!',
    concert: 'aespa MY WORLD TOUR',
    emotion: '🔥',
    likes: 234,
    comments: 47,
    isLiked: false,
    createdAt: '2025-11-16T08:30:00Z',
    tags: ['aespa', '에스파', '인생공연'],
  },
  {
    id: 'post_002',
    author: {
      uid: 'user_003',
      nickname: '콘서트홀릭',
      profileEmoji: '🎵',
      isPublic: true,
    },
    content: '뉴진스 버니즈캠프 2일차! 어제보다 오늘 더 좋았어요. 하니가 한국 팬들한테 직접 편지 읽어줬을 때 눈물 바다였음 ㅠㅠ 분위기 너무 포근하고 따뜻했어요',
    concert: 'NewJeans Bunnies Camp',
    emotion: '💕',
    likes: 189,
    comments: 31,
    isLiked: true,
    createdAt: '2025-09-08T14:20:00Z',
    tags: ['NewJeans', '뉴진스', '버니즈캠프'],
  },
  {
    id: 'post_003',
    author: {
      uid: 'user_004',
      nickname: '음악탐정',
      profileEmoji: '🎸',
      isPublic: true,
    },
    content: '콜드플레이 내한 예매 성공했습니다!!!! 손 떨리다가 결제 완료되는 순간 진짜 울었어요 ㅠㅠ 같이 갈 공연메이트 구해요~ 5/28(수) 서울월드컵경기장 같은 구역이면 좋겠어요',
    concert: 'Coldplay Music of the Spheres',
    emotion: '😭',
    likes: 312,
    comments: 88,
    isLiked: false,
    createdAt: '2026-03-16T22:10:00Z',
    tags: ['Coldplay', '콜드플레이', '공연메이트구해요'],
  },
  {
    id: 'post_004',
    author: {
      uid: 'user_005',
      nickname: '달빛여행자',
      profileEmoji: '🌙',
      isPublic: false,
    },
    content: 'IU 공연은 역시 다르다... 비 오는 날 야외에서 밤편지 들을 때 진짜 현실인지 몰랐어요. 음악이 이렇게 사람의 마음을 움직일 수 있다는 게 새삼 신기했습니다 🌧️',
    concert: 'IU H.E.R. World Tour',
    emotion: '😭',
    likes: 445,
    comments: 62,
    isLiked: true,
    createdAt: '2025-06-21T10:00:00Z',
    tags: ['IU', '아이유', '밤편지'],
  },
];

export const mockChats = [
  {
    id: 'chat_001',
    user: {
      uid: 'user_006',
      nickname: '스파클링',
      profileEmoji: '✨',
    },
    lastMessage: '5/28 같은 구역이세요?',
    lastMessageAt: '2026-05-11T14:30:00Z',
    expiresAt: '2026-05-13T14:30:00Z',
    unread: 2,
    isExpired: false,
  },
  {
    id: 'chat_002',
    user: {
      uid: 'user_007',
      nickname: '핑크드림',
      profileEmoji: '🌸',
    },
    lastMessage: 'aespa 다음 공연도 같이 가실래요?',
    lastMessageAt: '2026-05-10T20:15:00Z',
    expiresAt: '2026-05-12T20:15:00Z',
    unread: 0,
    isExpired: false,
  },
  {
    id: 'chat_003',
    user: {
      uid: 'user_008',
      nickname: '새벽세시',
      profileEmoji: '🌃',
    },
    lastMessage: '좋은 자리였어요! 다음에 또 봬요',
    lastMessageAt: '2026-05-08T23:00:00Z',
    expiresAt: '2026-05-10T23:00:00Z',
    unread: 0,
    isExpired: true,
  },
];

export const mockMessages = {
  chat_001: [
    { id: 'msg_001', senderId: 'user_006', text: '안녕하세요! 콜드플레이 공연 가시나요?', createdAt: '2026-05-11T14:20:00Z' },
    { id: 'msg_002', senderId: 'user_001', text: '네! 5/28 가요 ㅎㅎ', createdAt: '2026-05-11T14:22:00Z' },
    { id: 'msg_003', senderId: 'user_006', text: '저도요! 혹시 어느 구역이세요?', createdAt: '2026-05-11T14:25:00Z' },
    { id: 'msg_004', senderId: 'user_006', text: '5/28 같은 구역이세요?', createdAt: '2026-05-11T14:30:00Z' },
  ],
};

export const emotionOptions = [
  { emoji: '🔥', label: '흥분' },
  { emoji: '💕', label: '설레임' },
  { emoji: '😭', label: '감동' },
  { emoji: '🥹', label: '벅참' },
  { emoji: '😊', label: '행복' },
  { emoji: '🤩', label: '황홀' },
  { emoji: '💜', label: '사랑' },
  { emoji: '😤', label: '아쉬움' },
  { emoji: '🥳', label: '신남' },
  { emoji: '🌙', label: '몽환' },
];

export const weatherOptions = [
  { emoji: '☀️', label: '맑음' },
  { emoji: '⛅', label: '흐림' },
  { emoji: '🌧️', label: '비' },
  { emoji: '❄️', label: '눈' },
  { emoji: '🌩️', label: '천둥' },
  { emoji: '🌈', label: '무지개' },
  { emoji: '🌙', label: '밤' },
  { emoji: '💨', label: '바람' },
];

export const genreOptions = ['K-POP', '팝', '록', 'R&B', '힙합', '재즈', '인디', '클래식', '발라드', '댄스'];
